use axum::{
    extract::{Query, State},
    http::StatusCode,
    response::IntoResponse,
    Json,
};
use serde::Deserialize;

use crate::server::{AppState, err};


pub(crate) async fn stats(State(state): State<AppState>) -> Json<serde_json::Value> {
    let store = state.store.lock().await;
    let s = store.stats().clone();
    Json(serde_json::json!({
        "started": s.started,
        "chunks_served": s.chunks_served,
        "bytes_served": s.bytes_served,
        "chunks_stored": s.chunks_stored,
        "bytes_ingested": s.bytes_ingested,
        "requests_total": s.requests_total,
        "total_chunks": store.chunk_count(),
        "total_bytes": store.total_bytes(),
    }))
}


// ---------------------------------------------------------------------------
// Stats handlers
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
pub struct StatsPeriodQuery {
    pub period_hours: Option<u64>,
    pub period_days: Option<u64>,
    pub limit: Option<usize>,
}


pub(crate) async fn stats_downloads(
    State(state): State<AppState>,
    Query(q): Query<StatsPeriodQuery>,
) -> impl IntoResponse {
    let period_hours = q.period_hours.unwrap_or(168); // 7 days default
    match state.stats.download_stats(period_hours) {
        Ok(s) => (StatusCode::OK, Json(serde_json::to_value(s).unwrap_or_default())).into_response(),
        Err(e) => err(StatusCode::INTERNAL_SERVER_ERROR, &e.to_string()).into_response(),
    }
}


pub(crate) async fn stats_hot_chunks(
    State(state): State<AppState>,
    Query(q): Query<StatsPeriodQuery>,
) -> impl IntoResponse {
    let limit = q.limit.unwrap_or(20);
    match state.stats.hot_chunks(limit) {
        Ok(chunks) => {
            let count = chunks.len();
            (StatusCode::OK, Json(serde_json::json!({"hot_chunks": chunks, "count": count}))).into_response()
        }
        Err(e) => err(StatusCode::INTERNAL_SERVER_ERROR, &e.to_string()).into_response(),
    }
}


pub(crate) async fn stats_replication_advice(State(state): State<AppState>) -> impl IntoResponse {
    match state.stats.replication_advice() {
        Ok(advice) => {
            let count = advice.len();
            (StatusCode::OK, Json(serde_json::json!({"advice": advice, "count": count}))).into_response()
        }
        Err(e) => err(StatusCode::INTERNAL_SERVER_ERROR, &e.to_string()).into_response(),
    }
}


pub(crate) async fn stats_ingest_history(
    State(state): State<AppState>,
    Query(q): Query<StatsPeriodQuery>,
) -> impl IntoResponse {
    let period_days = q.period_days.unwrap_or(365);
    match state.stats.ingest_history(period_days) {
        Ok(h) => (StatusCode::OK, Json(serde_json::to_value(h).unwrap_or_default())).into_response(),
        Err(e) => err(StatusCode::INTERNAL_SERVER_ERROR, &e.to_string()).into_response(),
    }
}


// ---------------------------------------------------------------------------
// Coverage + extra stats handlers
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
pub struct CoverageQuery {
    pub source: Option<String>,
}

pub(crate) async fn coverage_spatial(
    State(state): State<AppState>,
    Query(q): Query<CoverageQuery>,
) -> impl IntoResponse {
    let force_local = q.source.as_deref() == Some("local");

    // If running as beacon (and not forced local), serve aggregated coverage from all nodes
    if state.is_beacon && !force_local {
        let beacon_db_path = state.data_dir.join("beacon.db");
        if beacon_db_path.exists() {
            if let Ok(reg) = crate::beacon::BeaconRegistry::new(&beacon_db_path) {
                match reg.get_aggregated_coverage() {
                    Ok(coverage) => return (StatusCode::OK, Json(coverage)).into_response(),
                    Err(e) => eprintln!("⚠️  Beacon aggregated coverage failed: {}", e),
                }
            }
        }
    }

    // Serve pre-computed MGRS tile polygons (generated by Python with pyproj)
    let poly_path = state.data_dir.join("coverage_spatial.json");
    if poly_path.exists() {
        match std::fs::read_to_string(&poly_path) {
            Ok(json_str) => {
                match serde_json::from_str::<serde_json::Value>(&json_str) {
                    Ok(val) => return (StatusCode::OK, Json(val)).into_response(),
                    Err(_) => {}
                }
            }
            Err(_) => {}
        }
    }

    // Fallback: bbox-based coverage from DB
    let catalog = state.catalog.lock().await;
    let tiles = catalog.mgrs_coverage().unwrap_or_default();
    let mut collections: std::collections::HashMap<String, Vec<serde_json::Value>> =
        std::collections::HashMap::new();
    for t in &tiles {
        collections.entry(t.collection.clone()).or_default().push(
            serde_json::json!({
                "bbox": [t.west, t.south, t.east, t.north],
                "tile_id": t.tile_id,
                "date_count": t.date_count,
            })
        );
    }
    let col_map: serde_json::Value = collections
        .into_iter()
        .map(|(k, v)| (k, serde_json::json!({ "cells": v })))
        .collect();

    (StatusCode::OK, Json(serde_json::json!({
        "collections": col_map,
    }))).into_response()
}


pub(crate) async fn stats_coverage(State(state): State<AppState>) -> impl IntoResponse {
    let catalog = state.catalog.lock().await;
    let total = catalog.item_count(None).unwrap_or(0);
    let collections = catalog.list_collections().unwrap_or_default();
    let per_col: Vec<serde_json::Value> = collections
        .iter()
        .map(|c| {
            let count = catalog.item_count(Some(&c.id)).unwrap_or(0);
            serde_json::json!({ "collection": c.id, "item_count": count })
        })
        .collect();
    (StatusCode::OK, Json(serde_json::json!({
        "total_items": total,
        "collections": per_col,
    }))).into_response()
}


pub(crate) async fn stats_requests(State(state): State<AppState>) -> impl IntoResponse {
    let store = state.store.lock().await;
    let s = store.stats().clone();
    (StatusCode::OK, Json(serde_json::json!({
        "requests_total": s.requests_total,
        "chunks_served": s.chunks_served,
        "bytes_served": s.bytes_served,
    }))).into_response()
}


pub(crate) async fn stats_bandwidth(State(state): State<AppState>) -> impl IntoResponse {
    let store = state.store.lock().await;
    let s = store.stats().clone();
    (StatusCode::OK, Json(serde_json::json!({
        "bytes_served": s.bytes_served,
        "bytes_ingested": s.bytes_ingested,
        "gb_served": s.bytes_served as f64 / 1_073_741_824.0,
        "gb_ingested": s.bytes_ingested as f64 / 1_073_741_824.0,
    }))).into_response()
}


pub(crate) async fn bandwidth_handler(State(state): State<AppState>) -> impl IntoResponse {
    stats_bandwidth(State(state)).await
}


pub(crate) async fn stats_replication_status(State(state): State<AppState>) -> impl IntoResponse {
    match state.stats.replication_advice() {
        Ok(advice) => {
            let total = advice.len();
            (StatusCode::OK, Json(serde_json::json!({
                "total_items_checked": total,
                "advice": advice,
            }))).into_response()
        }
        Err(e) => err(StatusCode::INTERNAL_SERVER_ERROR, &e.to_string()).into_response(),
    }
}


// ---------------------------------------------------------------------------
// Stats: access statistics
// ---------------------------------------------------------------------------

pub(crate) async fn stats_access(State(state): State<AppState>) -> impl IntoResponse {
    match state.stats.replication_advice() {
        Ok(advice) => {
            (StatusCode::OK, Json(serde_json::json!({
                "top_collections": advice,
                "note": "Access-based replication advice",
            }))).into_response()
        }
        Err(e) => err(StatusCode::INTERNAL_SERVER_ERROR, &e.to_string()).into_response(),
    }
}


// ---------------------------------------------------------------------------
// Stats: stats.json (alias for /stats)
// ---------------------------------------------------------------------------

pub(crate) async fn stats_json_alias(State(state): State<AppState>) -> impl IntoResponse {
    // Serve dashboard_stats.json if it exists (generated by update_stats.sh)
    let dashboard_path = state.data_dir.join("dashboard_stats.json");
    if dashboard_path.exists() {
        match std::fs::read_to_string(&dashboard_path) {
            Ok(content) => {
                match serde_json::from_str::<serde_json::Value>(&content) {
                    Ok(val) => return (StatusCode::OK, Json(val)).into_response(),
                    Err(_) => {}
                }
            }
            Err(_) => {}
        }
    }
    // Fallback: build combined stats with ingest + uptake
    let store = state.store.lock().await;
    let _s = store.stats().clone();
    let total_chunks = store.chunk_count();
    let total_bytes = store.total_bytes();
    drop(store);

    // Ingest history (30 days)
    let ingest = state.stats.ingest_history(30).ok().map(|h| {
        serde_json::json!({
            "total_gb_fetched": h.total_bytes as f64 / 1_073_741_824.0,
            "total_items": h.total_items,
            "daily": h.daily,
            "hourly": h.hourly,
        })
    }).unwrap_or(serde_json::json!({}));

    // Uptake summary (30 days)
    let uptake = state.stats.ingest_history(30).ok().map(|h| {
        let total_gb = h.total_bytes as f64 / 1_073_741_824.0;
        serde_json::json!({
            "summary": {
                "total_requests": h.total_items,
                "total_gb": (total_gb * 1000.0).round() / 1000.0,
            }
        })
    }).unwrap_or(serde_json::json!({}));

    // Network info placeholder (beacon.html fetches /beacon/nodes separately)
    let network = serde_json::json!({});

    let catalog = state.catalog.lock().await;
    let items = catalog.item_count(None).unwrap_or(0);
    drop(catalog);

    (StatusCode::OK, Json(serde_json::json!({
        "version": state.version,
        "chunks": total_chunks,
        "items": items,
        "coverage": { "total_bytes": total_bytes },
        "network": network,
        "ingest": ingest,
        "uptake": uptake,
        "updated": chrono::Utc::now().to_rfc3339(),
    }))).into_response()
}


// ---------------------------------------------------------------------------
// Stats: uptake (anonymous aggregate)
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
pub struct UptakePeriodQuery {
    pub period_days: Option<u64>,
}


pub(crate) async fn stats_uptake(
    State(state): State<AppState>,
    Query(q): Query<UptakePeriodQuery>,
) -> impl IntoResponse {
    let period_days = q.period_days.unwrap_or(30);
    // Use ingest_history as a proxy for uptake data
    match state.stats.ingest_history(period_days) {
        Ok(history) => {
            let total_gb = history.total_bytes as f64 / 1_073_741_824.0;
            (StatusCode::OK, Json(serde_json::json!({
                "report_type": "EarthGrid Uptake Statistics",
                "period_days": period_days,
                "privacy": "anonymous — no user identification stored",
                "summary": {
                    "total_requests": history.total_items,
                    "total_gb": (total_gb * 1000.0).round() / 1000.0,
                    "total_bytes": history.total_bytes,
                },
                "daily_trend": history.daily.iter().map(|d| serde_json::json!({
                    "date": d.date,
                    "items": d.items,
                    "gb": d.gb,
                })).collect::<Vec<_>>(),
                "hourly_trend": history.hourly.iter().map(|h| serde_json::json!({
                    "hour": h.hour,
                    "items": h.items,
                    "bytes": h.bytes,
                })).collect::<Vec<_>>(),
            }))).into_response()
        }
        Err(e) => err(StatusCode::INTERNAL_SERVER_ERROR, &e.to_string()).into_response(),
    }
}


pub(crate) async fn stats_uptake_csv(
    State(state): State<AppState>,
    Query(q): Query<UptakePeriodQuery>,
) -> impl IntoResponse {
    let period_days = q.period_days.unwrap_or(30);
    match state.stats.ingest_history(period_days) {
        Ok(history) => {
            let mut csv = String::from("date,items,bytes_ingested,gb_ingested\n");
            for d in &history.daily {
                csv.push_str(&format!("{},{},{},{:.3}\n", d.date, d.items, d.bytes, d.gb));
            }
            let disp = format!("attachment; filename=\"earthgrid_uptake_{}d.csv\"", period_days);
            let mut headers = axum::http::HeaderMap::new();
            headers.insert(
                axum::http::header::CONTENT_TYPE,
                axum::http::HeaderValue::from_static("text/csv"),
            );
            if let Ok(val) = axum::http::HeaderValue::from_str(&disp) {
                headers.insert(axum::http::header::CONTENT_DISPOSITION, val);
            }
            (StatusCode::OK, headers, csv).into_response()
        }
        Err(e) => err(StatusCode::INTERNAL_SERVER_ERROR, &e.to_string()).into_response(),
    }
}

