services:
  earthgrid:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: earthgrid
    ports:
      - "8400:8400"
    volumes:
      - earthgrid-data:/data
    environment:
      - EARTHGRID_NODE_NAME=node-alpha
      - EARTHGRID_PORT=8400
      - EARTHGRID_ALSO_BEACON=true
    restart: unless-stopped
    cpu_shares: 128
    cpuset: ""
    mem_limit: 2g
    oom_score_adj: 500

volumes:
  earthgrid-data:
